apiVersion: v1
kind: ConfigMap
metadata:
  name: accounts-mongo-config
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
    net:
      port: 27017
      bindIpAll: true
    security:
      authorization: "enabled"
      keyFile: "/home/mongodb/keyFile"
