apiVersion: v1
kind: Secret
metadata:
  name: accounts-mongo-secret
data:
  MONGO_INITDB_ROOT_PASSWORD: bXQta3MucGFzc3dvcmQuMQ== # mt-ks.password.1
  MONGO_PASSWORD: bXQta3MucGFzc3dvcmQuMQ== # mt-ks.password.1
