apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: mtks/starrent-account-service
          name: account
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: accounts-mongo-env
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accounts-mongo-secret
                  key: MONGO_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: accounts-mongo-env
                  key: MONGO_INITDB_DATABASE
            - name: MONGODB_REPLICASET_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@accounts-mongo-0.accounts-mongo-service:27017,accounts-mongo-1.accounts-mongo-service:27017,accounts-mongo-2.accounts-mongo-service:27017/$(MONGO_INITDB_DATABASE)?replicaSet=rs0"

---
apiVersion: v1
kind: Service
metadata:
  name: account-depl
spec:
  selector:
    app: account
  ports:
    - name: account
      port: 3000
      targetPort: 3000
      protocol: TCP
